/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.page_information.PageScreenshot', null, global);
goog.exportSymbol('proto.page_information.PageUrl', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.page_information.PageUrl = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.page_information.PageUrl, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.page_information.PageUrl.displayName = 'proto.page_information.PageUrl';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.page_information.PageUrl.prototype.toObject = function(opt_includeInstance) {
  return proto.page_information.PageUrl.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.page_information.PageUrl} msg The msg instance to transform.
 * @return {!Object}
 */
proto.page_information.PageUrl.toObject = function(includeInstance, msg) {
  var f, obj = {
    pageUrl: msg.getPageUrl()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.page_information.PageUrl}
 */
proto.page_information.PageUrl.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.page_information.PageUrl;
  return proto.page_information.PageUrl.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.page_information.PageUrl} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.page_information.PageUrl}
 */
proto.page_information.PageUrl.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.page_information.PageUrl} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.page_information.PageUrl.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.page_information.PageUrl.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.page_information.PageUrl.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getPageUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.page_information.PageUrl} The clone.
 */
proto.page_information.PageUrl.prototype.cloneMessage = function() {
  return /** @type {!proto.page_information.PageUrl} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string page_url = 1;
 * @return {string}
 */
proto.page_information.PageUrl.prototype.getPageUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.page_information.PageUrl.prototype.setPageUrl = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.page_information.PageScreenshot = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.page_information.PageScreenshot.repeatedFields_, null);
};
goog.inherits(proto.page_information.PageScreenshot, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.page_information.PageScreenshot.displayName = 'proto.page_information.PageScreenshot';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.page_information.PageScreenshot.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.page_information.PageScreenshot.prototype.toObject = function(opt_includeInstance) {
  return proto.page_information.PageScreenshot.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.page_information.PageScreenshot} msg The msg instance to transform.
 * @return {!Object}
 */
proto.page_information.PageScreenshot.toObject = function(includeInstance, msg) {
  var f, obj = {
    screenshot: msg.getScreenshot(),
    success: msg.getSuccess(),
    status: msg.getStatus(),
    errorsList: jspb.Message.getField(msg, 4)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.page_information.PageScreenshot}
 */
proto.page_information.PageScreenshot.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.page_information.PageScreenshot;
  return proto.page_information.PageScreenshot.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.page_information.PageScreenshot} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.page_information.PageScreenshot}
 */
proto.page_information.PageScreenshot.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setScreenshot(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStatus(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.getErrorsList().push(value);
      msg.setErrorsList(msg.getErrorsList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.page_information.PageScreenshot} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.page_information.PageScreenshot.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.page_information.PageScreenshot.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.page_information.PageScreenshot.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getScreenshot();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getSuccess();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = this.getStatus();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = this.getErrorsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.page_information.PageScreenshot} The clone.
 */
proto.page_information.PageScreenshot.prototype.cloneMessage = function() {
  return /** @type {!proto.page_information.PageScreenshot} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string screenshot = 1;
 * @return {string}
 */
proto.page_information.PageScreenshot.prototype.getScreenshot = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.page_information.PageScreenshot.prototype.setScreenshot = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional bool success = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.page_information.PageScreenshot.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 2, false));
};


/** @param {boolean} value  */
proto.page_information.PageScreenshot.prototype.setSuccess = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional int32 status = 3;
 * @return {number}
 */
proto.page_information.PageScreenshot.prototype.getStatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.page_information.PageScreenshot.prototype.setStatus = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * repeated string errors = 4;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<string>}
 */
proto.page_information.PageScreenshot.prototype.getErrorsList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getField(this, 4));
};


/** @param {Array.<string>} value  */
proto.page_information.PageScreenshot.prototype.setErrorsList = function(value) {
  jspb.Message.setField(this, 4, value || []);
};


proto.page_information.PageScreenshot.prototype.clearErrorsList = function() {
  jspb.Message.setField(this, 4, []);
};


goog.object.extend(exports, proto.page_information);
